print('olá mundo')
print('eu sou o maior otario que já existiu na face da terra')
print('neymar errou ao ir para o psg')
print('cr7 é mais foda que o messi')
print('graduation é o melhor álbum do kanye west')
print('a seleçao brasileira é paia')
print('mãe eu vou pra loud')
print('sou apenas um aprendiz atualmente')
print('kendrick lamar é melhor que drake')
print('corinthians')
